[package]
name = "dynamic-derive"
version = "0.1.0"
authors = ["Sascha Wise <me@saschawise.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.12"
proc-macro2 = "1"
syn = "1"
quote = "1.0.2"

[dev-dependencies]
dynamic = { path = "../dynamic" }
trybuild = "1.0"
